### ISSUE TITLE
«count(): Parameter must be an array or an object that implements Countable in app/code/core/Mage/Wishlist/Model/Observer.php on line 105»

### ISSUE THREAD

**Issue by dmitrii-fediuk** [etripbikes/m1#7]
Related to https://github.com/etripbikes/m1/issues/5
Similar to https://github.com/etripbikes/m1/issues/6

```
2022-08-28T04:34:34+00:00 DEBUG (7): Exception message: Warning: count(): Parameter must be an array or an object that implements Countable  in app/code/core/Mage/Wishlist/Model/Observer.php on line 105
Trace: #0 app/code/core/Mage/Wishlist/Model/Observer.php(105): mageCoreErrorHandler(2, 'count(): Parame...', 'C://work//clients...', 105, Array)
#1 app/code/core/Mage/Core/Model/App.php(1358): Mage_Wishlist_Model_Observer->processAddToCart(Object(Varien_Event_Observer))
#2 app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Wishlist_Model_Observer), 'processAddToCar...', Object(Varien_Event_Observer))
#3 app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('checkout_cart_a...', Array)
#4 app/code/core/Mage/Checkout/controllers/CartController.php(248): Mage::dispatchEvent('checkout_cart_a...', Array)
#5 app/code/core/Mage/Core/Controller/Varien/Action.php(418): Mage_Checkout_CartController->addAction()
#6 app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('add')
#7 app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#8 app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#9 app/Mage.php(683): Mage_Core_Model_App->run(Array)
#10 index.php(83): Mage::run('', 'store')
#11 {main}
```

**Comment by dmitrii-fediuk** [comment]
The issue is fixed in newer Magento versions, e.g.: https://github.com/OpenMage/magento-mirror/blob/1.9.4.5/app/code/core/Mage/Wishlist/Model/Observer.php#L105
So https://github.com/etripbikes/m1/issues/4 will solve it.
